# COMP90024 Team 75 
# Linying Wei (1638206)
# Wangyang Wu (1641248)
# Ziyu Wang (1560831)
# Roger Zhang (1079986)

apiVersion: v1
kind: ConfigMap
metadata:
  namespace: default
  name: shared-data
data:
  ES_USERNAME: elastic
  ES_PASSWORD: elastic
  MASTODON_ACCESS_TOKEN: Yu3vIqle07o8NLKx4hjcjHKu5GMA2FuOXJ-ZWvH5fVg